### PR TITLE
Initial work for the onboarding/community documentation

### LINKED ISSUE #31: Create an onboarding process/document
We need to figure out an onboarding process, so that other people interested in participating can join in. There's some parts that we can tackle from a GitHub point of view, or within the project repo (such as a `CONTRIBUTING.md` file). More research will need to be done to figure out something that'll get developers interested in the project to be able to pick up and go, and for the contribution to be accepted.

# Possible Solutions

- GitHub
    - Pull request template: This is still very early. While we want to make sure the contributions are high quality, it is a lot of things to keep track of. Maybe could put the checklist in its own file and refer to it in the PR template.
    - Issue tags: We could tag issues with help wanted and good first issue. Probably worth triaging issues as they come in and tag them.
- Project
    - Add a `CONTRIBUTING.md` document to describe how to contribute and what to do when.
    - Add some training material on how to get set up and ready to go. For example, we could set up a document for "how to use VSCode's container feature to get started".

# URLs

## Example contributing files

- https://github.com/AcademySoftwareFoundation/openexr/blob/master/CONTRIBUTING.md
- https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/CONTRIBUTING.md
- https://www.opencue.io/contributing/opencue/contributing/
- https://github.com/AcademySoftwareFoundation/openvdb/blob/master/CONTRIBUTING.md
- https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/master/CONTRIBUTING.md

## Onboarding information

- https://swimm.io/blog/4-ways-to-improve-developer-onboarding-to-your-open-source-project/
- https://mozillascience.github.io/working-open-workshop/contributing/
- https://opensource.com/article/19/12/open-source-contributors

### PR DESCRIPTION
**Pull request by scott-wilson**
This is the initial work for the OpenEXR Bindings project onboarding and community documentation.

It isn't complete at the moment, but is meant to be the starting point of discussions.

Closes #31

### CODE REVIEW

**Comment by anderslanglands** [comment]
Looks like a great start, thanks Scott! My only thought is that we could use “openexr-bind” rather than “the OpenEXR Rust Bindings Project”, both for brevity and because on a diagonal read I kept thinking I was looking at documentation from OpenEXR itself so might be good to separate this more clearly?

**Comment by scott-wilson** [comment]
> Looks like a great start, thanks Scott! My only thought is that we could use “openexr-bind” rather than “the OpenEXR Rust Bindings Project”, both for brevity and because on a diagonal read I kept thinking I was looking at documentation from OpenEXR itself so might be good to separate this more clearly?

Yeah, I was wondering about that. I did borrow some of the text from OpenEXR, so some of the structure is the same.

**Comment by anderslanglands** [comment]
Only other thing to do would be to add a section to the README linking to these

**Comment by scott-wilson** [comment]
Notes from a discussion with one of the contributors for OCIO:

- Since our goal is to hand off ownership of the bindings, we need to figure out some of the legal stuff (CLA, signoff, etc.) Even though we probably don't need to worry about it now, OpenEXR, and other projects do need to worry.
- How to integrate our documentation with the wrapped libraries. For example, https://opencolorio.readthedocs.io/en/latest/api/grading_transforms.html has the Python and C++ bindings all in one page. They'd likely want the Rust bindings on the same page as well.
- Which license should we use (I think that it is BSD, but John Mertic is probably the best person to talk to).
- Make sure we go through the process of "I want to contribute", creating issues and pull requests, and having the PR approved. Also, a good thing to think about with diversity/inclusivity is to think about what are our expectations for someone contributing. For example, what's the minimal amount of Rust should someone know to contribute.
- Defining some goals/non goals of the OpenEXR crate. So, stuff like how close to the wrapped library do we want the crate, what functionality are we explicitly leaving out, etc.

**Comment by anderslanglands** [comment]
Looks good to me. Ready to merge?

**Pull request merged**
